"""empty message

Revision ID: cff975025ff3
Revises: 
Create Date: 2022-07-25 16:46:48.432478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cff975025ff3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('news_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('content', sa.String(length=500), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('flag', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('news_id')
    )
    op.create_table('users',
    sa.Column('users_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('uname', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('read_key', sa.String(length=100), nullable=False),
    sa.Column('write_key', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('users_id'),
    sa.UniqueConstraint('uname')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('news')
    # ### end Alembic commands ###
