"""empty message

Revision ID: dda6165ea0bb
Revises: cff975025ff3
Create Date: 2022-07-29 22:53:41.835163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dda6165ea0bb'
down_revision = 'cff975025ff3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('created_by', sa.Integer(), nullable=False))
    op.add_column('news', sa.Column('updated_by', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'updated_by')
    op.drop_column('news', 'created_by')
    # ### end Alembic commands ###
